### ISSUE TITLE
自己位置推定でOrientationのcovarianceが大きくなってしまう問題について

### ISSUE THREAD

**Issue by hozumikengo** [KBKN-Autonomous-Robotics-Lab/tsukuba2023-src#16]
概要
ナビゲーションにCLASの位置とmovingbaseの方位を使用するためにrobot_pose_ekfを使って
その際にOrientationのcovarianceが大きくなってしまう問題に直面しました。

手順
robot_pose_ekftest.launchの起動

2023-10-30nakaniwa.bagを再生

ここでrostopicの/combine_dr_measurements/odom_combinedを見るとOrientationのcovarianceが非常に大きくなってしまいます、、

その他
ここに検証で使用したバグやlaunchファイル、プログラムが載っています。
https://github.com/kengohozumi/CLASmovingbase

考えている原因
movingbaseの方位のpubの頻度が少ない
CLASの位置とmovingbaseの方位のpubの頻度の差によりOrientationの信頼が下がっている

**Comment by koki0624** [comment]
rostopic hz コマンドで、関連するトピックの周期を検証できませんか？

**Comment by hozumikengo** [comment]
<img width="378" alt="image" src="https://github.com/KBKN-Autonomous-Robotics-Lab/tsukuba2023-src/assets/83738796/a169a00a-ce31-4678-998e-dcf472c30112">

使っているメッセージは/movingbase/quatと/odom/gps をmessage_filtersにより合成して/CLAS_movingbase をpubしてrobot_pose_ekfから/combine_dr_measurements/odom_combinedがpubされています。

/movingbase/quatと/odom/gpsが頻度が違っていて
頻度が小さい/movingbase/quatのsubしているorientationのcovarianceが大きくなってしまっているのですかね、、？

**Comment by koki0624** [comment]
最終的にcovarianceを決定しているのは robot_pose_ekf 内部の拡張カルマンフィルタだと思うので、直接の原因かどうかわかりませんが、1つ気になることがあります。
> 使っているメッセージは/movingbase/quatと/odom/gps をmessage_filtersにより合成して/CLAS_movingbase をpubしてrobot_pose_ekfから/combine_dr_measurements/odom_combinedがpubされています。

message_filtersで同期しているなら、以下のコールバック関数は周期の長い方に合わせて実行されるはずです。
https://github.com/kengohozumi/CLASmovingbase/blob/6a79d6fd50102ecf84da5669d373d2299b12bba9/scripts/combination.py#L21-L23
つまり /moveingbase/quat の周期 1Hz で実行され、その時点での2つのメッセージデータを保持することになるかと思います。

これに対し、メインループは 10Hz で、その時点で保持している2つのデータを合成したオドメトリをパブリッシュしています。
https://github.com/kengohozumi/CLASmovingbase/blob/6a79d6fd50102ecf84da5669d373d2299b12bba9/scripts/combination.py#L52-L54

ということは、1秒間に約10回全く同じオドメトリデータをパブリッシュしていることになり、これは1秒間ロボットが停止しているのと同義になるのではないでしょうか。

同じ時間中のモーターのオドメトリやIMUのデータ上でロボットが動いていると推定される場合、これはカルマンフィルタによる推定に影響を与えていてもおかしくないように思います。

**Comment by hozumikengo** [comment]
rateを直してやってみたのですが、直りませんでした、、

**Comment by koki0624** [comment]
~~https://github.com/kengohozumi/CLASmovingbase/blob/6a79d6fd50102ecf84da5669d373d2299b12bba9/scripts/combination.py#L38-L43~~
~~covarianceの値は変えてみたりしましたか？~~ 

robot_pose_ekf で imu_used を false にしてオドメトリのみを入力とすると、モーターのオドメトリでも同様の現象が起きたので、movingbaseなどは無関係だと考えられます。
（先日話しましたが、issue なので記録として残しておきます。）


---

> rateを直してやってみたのですが、直りませんでした、、

covariance とは関係ありませんでしたが、推定に影響を与える問題であることは変わりないので修正が必要だと思います。
combination.py は while ループでオドメトリをパブリッシュするのではなく、/odom/gps と /movingbase/quat の同期をとったコールバックでパブリッシュするのが適切だと思います。

**Comment by hozumikengo** [comment]
月曜日に実機でどうなるか確認したいと思います。
パラメーターを強制的に変更する方法はtopic_toolsであっていますか？

**Comment by koki0624** [comment]
> 月曜日に実機でどうなるか確認したいと思います。 パラメーターを強制的に変更する方法はtopic_toolsであっていますか？

何のパラメータの話でしょうか？

**Comment by hozumikengo** [comment]
大きくなってしまっているcovarianceの値を後から強制的に小さくする方法です。

**Comment by koki0624** [comment]
モーターのオドメトリで同様の現象が起きているので、まずはimuも使った状態でのデータを見て比較する必要があるかと思います。
covarianceを小さくしなければならない場合があるとしたら、
- モーターオドメトリ+ imu ではcovarianceは大きくならない
- gpsオドメトリ+ imu ではcovarianceが大きくなり自己位置推定が上手くいかない
- 上記のとき、gpsオドメトリのcovariance以外の値はもっともらしい

といった場合になるかと思います。

**Comment by hozumikengo** [comment]
ありがとうございます
実機で検証、比較してみて、またここに結果をコメントしたいと思います。
message_filtersでodom/gpsはodomのrosメッセージ、/movingbase/quatはimuのrosメッセージを違う種類のrosmsgsを合成してるのもよくないですかね、、？

**Comment by koki0624** [comment]
> message_filtersでodom/gpsはodomのrosメッセージ、/movingbase/quatはimuのrosメッセージを違う種類のrosmsgsを合成してるのもよくないですかね、、？

message_filters は同じタイミングで2つのメッセージをサブスクライブしているだけなので、メッセージの型が異なることは特に問題ないと思います。

**Comment by hozumikengo** [comment]
今日実機で試してみて
エラーなくIMUとの合成ができました。

**Comment by hozumikengo** [comment]
![image](https://github.com/KBKN-Autonomous-Robotics-Lab/tsukuba2023-src/assets/83738796/32997b95-528b-49f8-8598-e3ad240960c2)
今日の結果はこうなりました。結構頻度が違います、、、。
それぞれ同じ場所を走行させいるだけで同時間に計測したわけではないので軌跡はそれぞれずれています。始点と終点(0,0)があっているかどうかを評価しています。グラフの単位はｍです。
IMUは結構補正してくれるみたいです。

**Comment by koki0624** [comment]
ひとまず、covariance は無関係という結論ですかね？

真値が分からないので何とも言えないですが、CLASを利用した場合の頻度や建物付近での安定性を考えれば、odom+imu が現状はベターなんでしょうか？
最終的にはそこにCLASを追加して補正できればベストだと思います。

**Comment by kengohozumi** [comment]
ありがとうございます。
covariance は無関係だったみたいです。
今robot localization でgpsを入れてできました。
あとはナビゲーションのパラメータを調整します。

**Comment by hozumikengo** [comment]
ありがとうございます。
covariance は無関係だったみたいです。
robot localization でgpsを入れてできました。
あとはナビゲーションのパラメータを調整します。
