### ISSUE TITLE
tsukuba2023-srcのブランチの取り扱いについて

### ISSUE THREAD

**Issue by Alpaca-zip** [KBKN-Autonomous-Robotics-Lab/tsukuba2023-src#2]
リポジトリの名前が`tsukuba2023-src`なので以下のような形で機体ごとにブランチ分けて開発しますか？
- `devel-orange2023`
- `devel-orange2023-jr`

**Comment by hozumikengo** [comment]
すいません　
ROS1とROS2で違う場合、全く違うプログラムのブランチを作るという意味でしょうか？

**Comment by Alpaca-zip** [comment]
> ROS1とROS2で違う場合、全く違うプログラムのブランチを作るという意味でしょうか？

そうです。ブランチ分けて開発するのであればROS1もROS2もあまり関係ないように思います。

**Comment by hozumikengo** [comment]
わかりました
ブランチ分けて開発します
M1はdevel-orange2023-middleのブランチで開発を行おうと思います

**Comment by Alpaca-zip** [comment]
@shunki1006 
ROS2側もそういう進め方で意見はありませんか？

**Comment by shunki1006** [comment]
ROS1, ROS2で全然違うと思うので分けて開発するので問題ないと思います

**Comment by Alpaca-zip** [comment]
> ROS1, ROS2で全然違うと思うので分けて開発するので問題ないと思います

これはtsukuba2023-srcというリポジトリに`devel-orange2023`というブランチを切って、orange_ros2の内容をコピーしてくるということです。これはorange_ros2というリポジトリがつくばチャレンジ用のリポジトリではいということを意味しますが、認識として合ってますか？

**Comment by shunki1006** [comment]
M1はROS1でつくばに出場すると聞いていたのですが、M1がdevel_orange2023の中でROS2環境も使いROS2の出場も考えているという認識であっていますか？

**Comment by Alpaca-zip** [comment]
> M1はROS1でつくばに出場すると聞いていたのですが、M1がdevel_orange2023の中でROS2環境も使いROS2の出場も考えているという認識であっていますか？

いや、違います。このtsukuba2023-srcは以下の3つのブランチを持つことになります。
- `devel-orange2023`
- `devel-orange2023-middle`
- `devel-orange2023-jr`

`devel-orange2023`はM2用のブランチで内容はROS2、`devel-orange2023-middle`はM1用のブランチで内容はROS1、`devel-orange2023-jr`は3年用のブランチで内容はROS2です。おそらく3年生はM2のプログラムから大きな変更はないと思うので、`devel-orange2023`と`devel-orange2023-jr`はほぼ同じになると思います。

**Comment by Alpaca-zip** [comment]
また、orange_ros2というリポジトリの運用方法も当初はつくばチャレンジを想定したものだったはずなので同じようなプログラムを置いてある場所が3つになります。しっかり運用方法を明確にするのであれば、このissueで提案した開発方法でも問題ないと思います。

**Comment by shunki1006** [comment]
orange_ros2はウェイポイントナビゲーションをROS2で行なうことを目的としたリポジトリとし、tsukuba2023-src内のdevel-orange2023ではつくばチャレンジ中の細かい調整やマッピングを行なうこととして使い分けるのが良いと思います。

**Comment by Alpaca-zip** [comment]
> orange_ros2はウェイポイントナビゲーションをROS2で行なうことを目的としたリポジトリとし、tsukuba2023-src内のdevel-orange2023ではつくばチャレンジ中の細かい調整やマッピングを行なうこととして使い分けるのが良いと思います。

おっけーです。tsukuba2023-srcで機体ごとにブランチを分けて開発を進める方針にしましょう。
@kengohozumi が既にpushしてくれている`main`ブランチは`devel-orange2023-middle`にして他は新しくブランチを切る形にします。
